baseURL = "http://weberjm.github.io/"
languageCode = "en-us"
title = "James Weber"
paginate = 5
contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true
Copyright = "All rights reserved - 2015"

[indexes]
   category = "categories"
   tag = "tags"
[Params]
  author = "James Weber"
  authorlocation = "Cologne, Germany"
  bio = "my bio"
  facebookName = "weberjm"
  github = "weberjm"
  twitter = "weberjm"
  description = "Thoughts on Tech, Business, and Life"
  linkedin = "weberjm"
  cover = "/images/background-cover.jpg"
  logo = "/images/logo.jpg"
